window.PLAYER_CHANNELS = [
  { name: "Fox 4K USA", language: "English", country: "us", quality: "4K", type: "Junkie", url: "https://junkieembeds.pages.dev/embed/fox4k-usa" },
  { name: "Telemundo USA", language: "Español", country: "us", quality: "HD", type: "Junkie", url: "https://junkieembeds.pages.dev/embed/telemundo-usa" },
  { name: "BBC 4K", language: "English", country: "gb", quality: "4K", type: "Junkie", url: "https://junkieembeds.pages.dev/embed/bbc-4k" },
  { name: "TSN 4K", language: "English", country: "ca", quality: "4K", type: "Junkie", url: "https://junkieembeds.pages.dev/embed/tsn-4k" },
  { name: "Fusball TV 1 UHD", language: "Español", country: "de", quality: "UHD", type: "Junkie", url: "https://junkieembeds.pages.dev/embed/fusballtv1uhd-de" },
  { name: "Fusball TV UHD", language: "Español", country: "de", quality: "UHD", type: "Junkie", url: "https://junkieembeds.pages.dev/embed/fusballtvuhd-de" },
  { name: "Dsports FHD", language: "Español", country: "world", quality: "1080p", type: "DRM", url: "https://sudamericaplay2.com/canal_8112/cza_dsports.html" },
  { name: "Trece HD", language: "Español", country: "py", quality: "720p", type: "DRM", url: "https://sudamericaplay2.com/canal_41/trecepy.php" },
  { name: "Fox ONE US FHD", language: "English", country: "us", quality: "1080p", type: "DRM", url: "https://sudamericaplay2.com/canal_8112/1foxone.html" },
  { name: "Dsports", language: "Español", country: "world", quality: "480p", type: "Global", url: "https://streamtpday1.xyz/global2.php?stream=dsports" },
  { name: "TyC Sports", language: "Español", country: "ar", quality: "480p", type: "Global", url: "https://streamtpday1.xyz/global1.php?stream=tycsports" },
  { name: "Telemundo", language: "Español", country: "us", quality: "480p", type: "Global", url: "https://streamtpday1.xyz/global2.php?stream=telemundousa" },
  { name: "TV LA 1 ES", language: "Español", country: "es", quality: "1080p", type: "DRM", url: "https://sudamericaplay2.com/canal_8112/tvla1es.html" },
  { name: "Caracol TV", language: "Español", country: "co", quality: "1080p", type: "DRM", url: "https://sudamericaplay2.com/canal_41/caracoltv.php" },
  { name: "RCN HD", language: "Español", country: "co", quality: "1080p", type: "DRM", url: "https://sudamericaplay2.com/canal_8112/rcn51.html" },
  { name: "MAX", language: "Español", country: "world", quality: "480p", type: "Global", url: "https://streamtpday1.xyz/global2.php?stream=max1" },
  { name: "Canal 5 MX", language: "Español", country: "mx", quality: "1080p", type: "DRM", url: "https://sudamericaplay2.com/canal_8112/21canalfive.html" },
  { name: "TUDN", language: "Español", country: "mx", quality: "1080p", type: "DRM", url: "https://sudamericaplay2.com/canal_8112/tudnmx.html" },
  {
    name: "Mundial 2026",
    category: "worldcup",
    language: "Español",
    country: "world",
    quality: "Multi",
    type: "Evento",
    options: [
      { name: "Opción 2", url: "https://sudamericaplay2.com/canal_8112/1dzportsplus.html" },
      { name: "Opción 3", url: "https://embedindia.st/embed/wc/2026-06-11/mex-rsa/telemundo" },
      { name: "Opción 4", url: "https://sudamericaplay2.com/canal_8112/74telemundo.html" },
      { name: "Opción 5", url: "https://sudamericaplay2.com/canal_8112/dsports4541.html" },
      { name: "Opción 6", url: "https://bestleague.top/tok.html?get=VGVsZWZlSEQ=" },
      { name: "Opción 7", url: "https://sudamericaplay2.com/canal_8112/tudnmx.html" },
      { name: "Opción 8", url: "https://sudamericaplay2.com/canal_41/caracoltv.php" },
      { name: "Opción 9", url: "https://sudamericaplay2.com/canal_8112/tvla1es.html" },
      { name: "Opción 10", url: "https://sudamericaplay2.com/canal_8112/zdf.html" },
      { name: "Opción 11", url: "https://sudamericaplay2.com/canal_8112/cazetv.html" },
      { name: "Opción 12", url: "https://sudamericaplay2.com/canal_8112/cza_dsports.html" },
      { name: "Opción 13", url: "https://stream-xhd.com/channel2/?id=dsports1" },
      { name: "Opción 14", url: "https://junkieembeds.pages.dev/embed/fox-usa" },
      { name: "Opción 15", url: "https://junkieembeds.pages.dev/embed/fox4k-usa" },
      { name: "Opción 16", url: "https://junkieembeds.pages.dev/embed/telemundo-usa" },
      { name: "Opción 18", url: "https://stream-xhd.com/channel2/?id=telemundo" },
      { name: "Opción 19", url: "https://sudamericaplay2.com/canal_8112/1foxone.html" },
      { name: "Opción 20", url: "https://stream-xhd.com/channel3/?id=foxoneusa" },
      { name: "Opción 21", url: "https://stream-xhd.com/live1.php?stream=foxoneusa" },
      { name: "Opción 22", url: "https://junkieembeds.pages.dev/embed/bbc-4k" },
      { name: "Opción 23", url: "https://junkieembeds.pages.dev/embed/bbcone-uk" },
      { name: "Opción 24", url: "https://junkieembeds.pages.dev/embed/sporttv1-pt" },
      { name: "Opción 25", url: "https://junkieembeds.pages.dev/embed/fusballtv1uhd-de" },
      { name: "Opción 26", url: "https://junkieembeds.pages.dev/embed/fusballtvuhd-de" },
      { name: "Opción 27", url: "https://junkieembeds.pages.dev/embed/fusballtv2uhd-de" },
      { name: "Opción 28", url: "https://junkieembeds.pages.dev/embed/cignal-ph" },
      { name: "Opción 29", url: "https://junkieembeds.pages.dev/embed/tsn1-ca" },
      { name: "Opción 30", url: "https://sudamericaplay2.com/canal_8112/tsn1.html" },
      { name: "Opción 31", url: "https://junkieembeds.pages.dev/embed/beinsports1-fr" },
      { name: "Opción 32", url: "https://junkieembeds.pages.dev/embed/beinsportsmax-sa" },
      { name: "Opción 33", url: "https://junkieembeds.pages.dev/embed/beinsportsmax3-sa" },
      { name: "Opción 34", url: "https://junkieembeds.pages.dev/embed/cazetv-br" },
      { name: "Opción 36", url: "https://stream-xhd.com/live1.php?stream=cazetv" },
      { name: "Opción 37", url: "https://junkieembeds.pages.dev/embed/dsports-ar" },
      { name: "Opción 38", url: "https://sudamericaplay2.com/canal_8112/21canalfive.html" },
      { name: "Opción 39", url: "https://stream-xhd.com/live1.php?stream=canal5mx" },
      { name: "Opción 40", url: "https://sudamericaplay2.com/canal_8112/vix123.html" },
      { name: "Opción 41", url: "https://stream-xhd.com/live1.php?stream=vix1" },
      { name: "Opción 43", url: "https://streamtpday1.xyz/global2.php?stream=dsports" },
      { name: "Opción 44", url: "https://la18hd.com/vivo/canales.php?stream=dsports" },
      { name: "Opción 45", url: "https://stream-xhd.com/live1.php?stream=dsports" },
      { name: "Opción 46", url: "https://streamtpday1.xyz/global1.php?stream=tycsports" },
      { name: "Opción 47", url: "https://la18hd.com/vivo/canales.php?stream=tycsports" },
      { name: "Opción 48", url: "https://stream-xhd.com/live1.php?stream=tycsports" },
      { name: "Opción 49", url: "https://streamtpday1.xyz/global2.php?stream=telemundousa" },
      { name: "Opción 50", url: "https://stream-xhd.com/live1.php?stream=telemundo" },
      { name: "Opción 51", url: "https://la18hd.com/vivo/canales.php?stream=vtvplus" },
      { name: "Opción 52", url: "https://stream-xhd.com/live1.php?stream=azteca7" },
      { name: "Opción 53", url: "https://stream-xhd.com/live1.php?stream=genpy" },
      { name: "Opción 54", url: "https://stream-xhd.com/live1.php?stream=trecepy" },
      { name: "Opción 56", url: "https://stream-xhd.com/channel2/?id=dsportsplus" },
      { name: "Opción 57", url: "https://stream-xhd.com/channel3/?id=fs1usa" },
      { name: "Opción 58", url: "https://stream-xhd.com/live1.php?stream=fs1usa" },
      { name: "Opción 59", url: "https://la18hd.com/vivo/canales.php?stream=foxsports1_usa" },
      { name: "Opción 60", url: "https://la18hd.com/vivo/canales.php?stream=dsportsplus" },
      { name: "Opción 61", url: "https://stream-xhd.com/live1.php?stream=dsportsplus" },
      { name: "Opción 62", url: "https://la18hd.com/vivo/canales.php?stream=eventos15" },
      { name: "Opción 63", url: "https://stream-xhd.com/live1.php?stream=unicanalpy" },
      { name: "Opción 65", url: "https://sudamericaplay2.com/canal_8112/rcn51.html" },
    ],
  },
];
